// <auto-generated />
using System;
using BE.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BE.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260422140831_UpdateSchemaV3")]
    partial class UpdateSchemaV3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BE.Models.CanBo", b =>
                {
                    b.Property<int>("MaCB")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaCB"));

                    b.Property<string>("ChucVu")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("MaKhoa")
                        .HasColumnType("int");

                    b.Property<int?>("MaPhong")
                        .HasColumnType("int");

                    b.Property<int?>("MaTK")
                        .HasColumnType("int");

                    b.HasKey("MaCB");

                    b.HasIndex("MaKhoa");

                    b.HasIndex("MaPhong");

                    b.HasIndex("MaTK")
                        .IsUnique()
                        .HasFilter("[MaTK] IS NOT NULL");

                    b.ToTable("CANBO", (string)null);
                });

            modelBuilder.Entity("BE.Models.ChiTra", b =>
                {
                    b.Property<int>("MaChiTra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaChiTra"));

                    b.Property<int?>("MaCB_GiaiNgan")
                        .HasColumnType("int");

                    b.Property<int>("MaHoSo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayXacNhan")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("ChuaGiaiNgan");

                    b.HasKey("MaChiTra");

                    b.HasIndex("MaCB_GiaiNgan");

                    b.HasIndex("MaHoSo");

                    b.ToTable("CHITRA", (string)null);
                });

            modelBuilder.Entity("BE.Models.DSHocBong", b =>
                {
                    b.Property<int>("MaDS")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDS"));

                    b.Property<int>("MaCB_PheDuyet")
                        .HasColumnType("int");

                    b.Property<int>("MaDot")
                        .HasColumnType("int");

                    b.Property<string>("MaSV")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("NgayPheDuyet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("XepLoai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaDS");

                    b.HasIndex("MaCB_PheDuyet");

                    b.HasIndex("MaDot");

                    b.HasIndex("MaSV");

                    b.ToTable("DSHOCBONG", (string)null);
                });

            modelBuilder.Entity("BE.Models.DiemRenLuyen", b =>
                {
                    b.Property<int>("MaDRL")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDRL"));

                    b.Property<int>("DiemSo")
                        .HasColumnType("int");

                    b.Property<int>("HocKy")
                        .HasColumnType("int");

                    b.Property<int?>("MaCB_Nhap")
                        .HasColumnType("int");

                    b.Property<string>("MaSV")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("NamHoc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.HasKey("MaDRL");

                    b.HasIndex("MaCB_Nhap");

                    b.HasIndex("MaSV");

                    b.ToTable("DIEMRENLUYEN", (string)null);
                });

            modelBuilder.Entity("BE.Models.DotHocBong", b =>
                {
                    b.Property<int>("MaDot")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDot"));

                    b.Property<int>("HocKy")
                        .HasColumnType("int");

                    b.Property<string>("LoaiDot")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NamHoc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("KhoiTao");

                    b.HasKey("MaDot");

                    b.ToTable("DOTHOCBONG", (string)null);
                });

            modelBuilder.Entity("BE.Models.HoSoXetHocBong", b =>
                {
                    b.Property<int>("MaHoSo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoSo"));

                    b.Property<float>("DiemHocTap")
                        .HasColumnType("real");

                    b.Property<int>("DiemRenLuyen")
                        .HasColumnType("int");

                    b.Property<float>("GPA")
                        .HasColumnType("real");

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaCB_Duyet")
                        .HasColumnType("int");

                    b.Property<int>("MaDot")
                        .HasColumnType("int");

                    b.Property<string>("MaSV")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime>("NgayNop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("ChoXet");

                    b.Property<string>("XepLoaiHB")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaHoSo");

                    b.HasIndex("MaCB_Duyet");

                    b.HasIndex("MaDot");

                    b.HasIndex("MaSV");

                    b.ToTable("HOSOXETHOCBONG", (string)null);
                });

            modelBuilder.Entity("BE.Models.KetQuaHocTap", b =>
                {
                    b.Property<int>("MaDiem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDiem"));

                    b.Property<bool>("CoDiemF")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<float>("DiemHocTap")
                        .HasColumnType("real");

                    b.Property<float>("GPA")
                        .HasColumnType("real");

                    b.Property<int>("HocKy")
                        .HasColumnType("int");

                    b.Property<int?>("MaCB_Nhap")
                        .HasColumnType("int");

                    b.Property<string>("MaSV")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("NamHoc")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("SoTC")
                        .HasColumnType("int");

                    b.HasKey("MaDiem");

                    b.HasIndex("MaCB_Nhap");

                    b.HasIndex("MaSV");

                    b.ToTable("KETQUAHOCTAP", (string)null);
                });

            modelBuilder.Entity("BE.Models.KhieuNai", b =>
                {
                    b.Property<int>("MaKhieuNai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhieuNai"));

                    b.Property<int?>("MaCB_Duyet")
                        .HasColumnType("int");

                    b.Property<int>("MaHoSo")
                        .HasColumnType("int");

                    b.Property<string>("MinhChung")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("NgayGui")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime?>("NgayPhanHoi")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiDungPhanHoi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValue("ChoXuLy");

                    b.HasKey("MaKhieuNai");

                    b.HasIndex("MaCB_Duyet");

                    b.HasIndex("MaHoSo");

                    b.ToTable("KHIEUNAI", (string)null);
                });

            modelBuilder.Entity("BE.Models.Khoa", b =>
                {
                    b.Property<int>("MaKhoa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaKhoa"));

                    b.Property<string>("TenKhoa")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("MaKhoa");

                    b.ToTable("KHOA", (string)null);
                });

            modelBuilder.Entity("BE.Models.Lop", b =>
                {
                    b.Property<int>("MaLop")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaLop"));

                    b.Property<int>("MaKhoa")
                        .HasColumnType("int");

                    b.Property<string>("TenLop")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MaLop");

                    b.HasIndex("MaKhoa");

                    b.ToTable("LOP", (string)null);
                });

            modelBuilder.Entity("BE.Models.PhanBoKinhPhi", b =>
                {
                    b.Property<int>("MaPhanBo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhanBo"));

                    b.Property<decimal>("KinhPhi")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaDot")
                        .HasColumnType("int");

                    b.Property<int>("MaKhoa")
                        .HasColumnType("int");

                    b.Property<decimal>("MucHBLoaiKha")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MaPhanBo");

                    b.HasIndex("MaKhoa");

                    b.HasIndex("MaDot", "MaKhoa")
                        .IsUnique();

                    b.ToTable("PHANBOKINHPHI", (string)null);
                });

            modelBuilder.Entity("BE.Models.PhongBan", b =>
                {
                    b.Property<int>("MaPhong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaPhong"));

                    b.Property<string>("TenPhong")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("MaPhong");

                    b.ToTable("PHONGBAN", (string)null);
                });

            modelBuilder.Entity("BE.Models.SinhVien", b =>
                {
                    b.Property<string>("MaSV")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("MaLop")
                        .HasColumnType("int");

                    b.Property<int?>("MaTK")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("SDT")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)");

                    b.HasKey("MaSV");

                    b.HasIndex("MaLop");

                    b.HasIndex("MaTK")
                        .IsUnique()
                        .HasFilter("[MaTK] IS NOT NULL");

                    b.ToTable("SINHVIEN", (string)null);
                });

            modelBuilder.Entity("BE.Models.TaiKhoan", b =>
                {
                    b.Property<int>("MaTK")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTK"));

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("VaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.HasKey("MaTK");

                    b.HasIndex("TenDangNhap")
                        .IsUnique();

                    b.ToTable("TAIKHOAN", (string)null);
                });

            modelBuilder.Entity("BE.Models.CanBo", b =>
                {
                    b.HasOne("BE.Models.Khoa", "Khoa")
                        .WithMany("CanBos")
                        .HasForeignKey("MaKhoa");

                    b.HasOne("BE.Models.PhongBan", "PhongBan")
                        .WithMany("CanBos")
                        .HasForeignKey("MaPhong");

                    b.HasOne("BE.Models.TaiKhoan", "TaiKhoan")
                        .WithOne("CanBo")
                        .HasForeignKey("BE.Models.CanBo", "MaTK");

                    b.Navigation("Khoa");

                    b.Navigation("PhongBan");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("BE.Models.ChiTra", b =>
                {
                    b.HasOne("BE.Models.CanBo", "CanBoGiaiNgan")
                        .WithMany("ChiTras")
                        .HasForeignKey("MaCB_GiaiNgan");

                    b.HasOne("BE.Models.HoSoXetHocBong", "HoSoXetHocBong")
                        .WithMany("ChiTras")
                        .HasForeignKey("MaHoSo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CanBoGiaiNgan");

                    b.Navigation("HoSoXetHocBong");
                });

            modelBuilder.Entity("BE.Models.DSHocBong", b =>
                {
                    b.HasOne("BE.Models.CanBo", "CanBoPheDuyet")
                        .WithMany("DSHocBongs")
                        .HasForeignKey("MaCB_PheDuyet")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BE.Models.DotHocBong", "DotHocBong")
                        .WithMany("DSHocBongs")
                        .HasForeignKey("MaDot")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BE.Models.SinhVien", "SinhVien")
                        .WithMany("DSHocBongs")
                        .HasForeignKey("MaSV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CanBoPheDuyet");

                    b.Navigation("DotHocBong");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("BE.Models.DiemRenLuyen", b =>
                {
                    b.HasOne("BE.Models.CanBo", "CanBoNhap")
                        .WithMany("DiemRenLuyens")
                        .HasForeignKey("MaCB_Nhap");

                    b.HasOne("BE.Models.SinhVien", "SinhVien")
                        .WithMany("DiemRenLuyens")
                        .HasForeignKey("MaSV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CanBoNhap");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("BE.Models.HoSoXetHocBong", b =>
                {
                    b.HasOne("BE.Models.CanBo", "CanBoDuyet")
                        .WithMany("HoSoXetHocBongs")
                        .HasForeignKey("MaCB_Duyet");

                    b.HasOne("BE.Models.DotHocBong", "DotHocBong")
                        .WithMany("HoSoXetHocBongs")
                        .HasForeignKey("MaDot")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BE.Models.SinhVien", "SinhVien")
                        .WithMany("HoSoXetHocBongs")
                        .HasForeignKey("MaSV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CanBoDuyet");

                    b.Navigation("DotHocBong");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("BE.Models.KetQuaHocTap", b =>
                {
                    b.HasOne("BE.Models.CanBo", "CanBoNhap")
                        .WithMany("KetQuaHocTaps")
                        .HasForeignKey("MaCB_Nhap");

                    b.HasOne("BE.Models.SinhVien", "SinhVien")
                        .WithMany("KetQuaHocTaps")
                        .HasForeignKey("MaSV")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CanBoNhap");

                    b.Navigation("SinhVien");
                });

            modelBuilder.Entity("BE.Models.KhieuNai", b =>
                {
                    b.HasOne("BE.Models.CanBo", "CanBoDuyet")
                        .WithMany("KhieuNais")
                        .HasForeignKey("MaCB_Duyet");

                    b.HasOne("BE.Models.HoSoXetHocBong", "HoSoXetHocBong")
                        .WithMany("KhieuNais")
                        .HasForeignKey("MaHoSo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CanBoDuyet");

                    b.Navigation("HoSoXetHocBong");
                });

            modelBuilder.Entity("BE.Models.Lop", b =>
                {
                    b.HasOne("BE.Models.Khoa", "Khoa")
                        .WithMany("Lops")
                        .HasForeignKey("MaKhoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("BE.Models.PhanBoKinhPhi", b =>
                {
                    b.HasOne("BE.Models.DotHocBong", "DotHocBong")
                        .WithMany("PhanBoKinhPhis")
                        .HasForeignKey("MaDot")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BE.Models.Khoa", "Khoa")
                        .WithMany("PhanBoKinhPhis")
                        .HasForeignKey("MaKhoa")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DotHocBong");

                    b.Navigation("Khoa");
                });

            modelBuilder.Entity("BE.Models.SinhVien", b =>
                {
                    b.HasOne("BE.Models.Lop", "Lop")
                        .WithMany("SinhViens")
                        .HasForeignKey("MaLop")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BE.Models.TaiKhoan", "TaiKhoan")
                        .WithOne("SinhVien")
                        .HasForeignKey("BE.Models.SinhVien", "MaTK");

                    b.Navigation("Lop");

                    b.Navigation("TaiKhoan");
                });

            modelBuilder.Entity("BE.Models.CanBo", b =>
                {
                    b.Navigation("ChiTras");

                    b.Navigation("DSHocBongs");

                    b.Navigation("DiemRenLuyens");

                    b.Navigation("HoSoXetHocBongs");

                    b.Navigation("KetQuaHocTaps");

                    b.Navigation("KhieuNais");
                });

            modelBuilder.Entity("BE.Models.DotHocBong", b =>
                {
                    b.Navigation("DSHocBongs");

                    b.Navigation("HoSoXetHocBongs");

                    b.Navigation("PhanBoKinhPhis");
                });

            modelBuilder.Entity("BE.Models.HoSoXetHocBong", b =>
                {
                    b.Navigation("ChiTras");

                    b.Navigation("KhieuNais");
                });

            modelBuilder.Entity("BE.Models.Khoa", b =>
                {
                    b.Navigation("CanBos");

                    b.Navigation("Lops");

                    b.Navigation("PhanBoKinhPhis");
                });

            modelBuilder.Entity("BE.Models.Lop", b =>
                {
                    b.Navigation("SinhViens");
                });

            modelBuilder.Entity("BE.Models.PhongBan", b =>
                {
                    b.Navigation("CanBos");
                });

            modelBuilder.Entity("BE.Models.SinhVien", b =>
                {
                    b.Navigation("DSHocBongs");

                    b.Navigation("DiemRenLuyens");

                    b.Navigation("HoSoXetHocBongs");

                    b.Navigation("KetQuaHocTaps");
                });

            modelBuilder.Entity("BE.Models.TaiKhoan", b =>
                {
                    b.Navigation("CanBo");

                    b.Navigation("SinhVien");
                });
#pragma warning restore 612, 618
        }
    }
}
